### ISSUE TITLE
Issue with output dimensions

### ISSUE THREAD

**Issue by CatalinMustata** [chilipeppr/workspace-grbl#3]
I tried to run some Gcode produced by rapid-pcb through the jpadie workspace (as instructed for grbl 1.1).

Strange this is that, while the 3D Viewer showed everything correctly (and displayed the correct), when running the program I ended up with a much smaller cut than expected. I suspect this is a conversion issue between metric and imperial, but I can't figure out why this would happen as I'm always using metric.

At one point, Chilipeppr did ask me about the system and I remember clearly choosing `mm`. Any ideas on how to debug/solve this?

**Comment by chilipeppr** [comment]
That sounds like your steps/mm stepper motor settings could actually be
what's causing the problem. Did you change any of those settings recently?

It would seem that if you picked inch instead of mm, you'd get the ratio of
that conversion as well which would be pretty drastic. Is it really that
ratio?

My take here it's not chilipeppr, but rather just your grbl settings, but
not sure. Could you also post a screenshot of the whole chilipeppr page?
That may help us find something.

**Comment by CatalinMustata** [comment]
Yeah, you're right. After a good sound sleep I reached the same conclusion and I've just powered up my machine and looked at the settings. I've upgraded from GRBL 0.9j to 1.1f yesterday and switched from UGS to Chilipeppr at the same time... for some reason I didn't think it would be a GRBL issue.

Now looking at the settings, I noticed my step per mm was at 250. I found some settings from another chap that did the upgrade (for the same CNC) and he had it at 800. I've set mine up like that now and it does move correctly on all axes.

**Comment by chilipeppr** [comment]
Cool. Good guess then on the issue.

**Comment by CatalinMustata** [comment]
Yup. I'll close the issue now.

PS: This probably isn't the right place, but here's a suggestion regarding the UI. It would be a good idea to present the user with a popup after he starts a program, telling him to check that probes are disconnected and everything is good to go (just like the auto leveler does). I just messed up my probing wires now being too eager to start milling after auto-leveling and forgetting to remove them.
